# Generated by Django 4.0.2 on 2022-09-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_created_at_alter_category_updated_at_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.like')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('reviews', models.ManyToManyField(blank=True, to='store.Review')),
            ],
        ),
    ]
