# Generated by Django 4.0.2 on 2022-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_like_user_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
