# Generated by Django 4.1.1 on 2022-09-29 20:09

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(null=True, validators=[store.validators.check_valid_ratings]),
        ),
    ]
