# Generated by Django 4.1.1 on 2022-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_customers_customer_user'),
        ('store', '0007_rename_comment_review_review_alter_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='review_likes_count', to='base.customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='unliked_by',
            field=models.ManyToManyField(blank=True, related_name='review_unlikes_count', to='base.customer'),
        ),
    ]
