# Generated by Django 4.1.1 on 2022-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_customers_customer_user'),
        ('store', '0009_alter_like_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='favorite_users',
            field=models.ManyToManyField(
                blank=True, related_name='item_favorite_users', to='base.customer'),
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist_users',
            field=models.ManyToManyField(
                blank=True, related_name='item_wishlist_users', to='base.customer'),
        ),
        migrations.DeleteModel(
            name='BookMark',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
