# Generated by Django 4.1.1 on 2022-10-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_customers_customer_user'),
        ('store', '0009_alter_like_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wishlisted', models.BooleanField(default=False)),
                ('wishlisted_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'ordering': ('wishlisted_at',),
            },
        ),
        migrations.RenameModel(
            old_name='BookMark',
            new_name='Favourite',
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('-favourite_at',)},
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='bookmarked_at',
            new_name='favourite_at',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='is_bookmarked',
            new_name='is_favourite',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
