# Generated by Django 4.1.1 on 2022-10-06 15:38

import cart.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_item_favorite_users_alter_item_wishlist_users'),
        ('base', '0003_delete_customers_customer_user'),
        ('cart', '0002_rename_orders_order_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('valid_till', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='had_checkout',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='store.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_options',
            field=models.CharField(choices=[('1', 'cash on delivery'), ('2', 'net banking'), ('3', 'credit-card'), ('4', 'debit-card')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(validators=[cart.validators.item_count_ge_zero])),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='cart.ordereditem'),
        ),
    ]
