# Generated by Django 4.1.1 on 2022-10-07 01:47

import cart.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_customers_customer_user'),
        ('cart', '0004_ordereditem_price_alter_ordereditem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ManyToManyField(blank=True, to='cart.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='promo_code', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item_count',
            field=models.IntegerField(default=1, validators=[cart.validators.item_count_ge_zero]),
        ),
    ]
