# Generated by Django 4.1.1 on 2022-10-07 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_customers_customer_user'),
        ('cart', '0005_cart_promo_code_promocode_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=100)),
                ('valid_till', models.DateField(default=django.utils.timezone.now)),
                ('discount_amount', models.PositiveIntegerField()),
                ('user', models.ManyToManyField(blank=True, related_name='promo_code', to='base.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='promo_code',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='cart.coupon'),
        ),
    ]
